server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online-learning-platform-db
    username: root
    password: mySQLpassword2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # Gmail SMTP configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: heysamsunga52@gmail.com
    password: rooc fzan qwqy lqkk
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true